### ISSUE TITLE
MegaMenu slows down Magento dramaticly when having a lot of categories

### ISSUE THREAD

**Issue by ReindDooyeweerd** [benjy/MegaMenu#2]
I used the module on a client website and it was working fine untill we imported the 250+ categories (10 first level categories, +/_ 120 second level categories, the rest 3rd category level) and imported the 25.000 products.

With the module enabled page load times are rising to 23+ seconds and above. After disabling the 'MegaMenu' module page load times are dropping back to 1.2sec and lower.

Any thoughts about how to 'solve' this speed issue?

If you need an big installation to test on let me know.

**Comment by benjy** [comment]
Yeah, It'e the code that generates the brands for each product. The way it's implemented is slow (I always knew that) but I didn't know how else to do it at the time.

I have however rewritten that code already and will merge it in over the weekend for you.

**Comment by benjy** [comment]
@Vout  I've just pushed some changes that change the way the categories are selected and ensure the block gets cached.

If you're still having performance issues It would be great if you could send me a SQL dump to test with.

**Comment by ReindDooyeweerd** [comment]
It's a bit faster but still an huge performance drop. I'll try to see if i can find some improvements and also make an nice 'dump' for you so you can test with it.

Will be after the easter weekend though ;-)

**Comment by u12206050** [comment]
I am aware that this issue is old, but has anyone found a proper solution to this?
We are having the same problem, where adding more categories has a direct correlation to the frontend page loading speed

**Comment by benjy** [comment]
This extension is no longer supported and should not be used in production.
