### ISSUE TITLE
Could you add a "how to install" readme or add to Maganto Connect?

### ISSUE THREAD

**Issue by ajax08** [benjy/MegaMenu#3]
Hi,

This sounds great but i'm having trouble trying it, basically i've installed countless extensions before but usually when i'm done adding all the files whatever is that's meant to show up on the page simply does...but after adding all the files to my test server i'm still seeing my old nav bar and don't see this new one?

I copied the required files from the base folder over to my custom theme folder but still nothing?

Can you help? me love you long time?

thanks

**Comment by benjy** [comment]
It should appear on a out of the box installation. Did you copy the layout file across to your theme? It's hard for me to say without seeing what you've done.

**Comment by ajax08** [comment]
I transferred the files to my magento root, with everything it's it's correct place (app folder to app folder etc) and i then copied the data from default/default to my custom theme but nothing happens.

i even tried using different themes but still nothing, the only read me i can find included in this is the file stating features and compatibility.

I'm using magento 1.7.0.2

thanks

**Comment by benjy** [comment]
I never created thorough installation instructions because it's more targeted for developers to use as a base. If you manage to get it working feel free to create a pull request with any instructions.

**Comment by benjy** [comment]
This extension is no longer supported.
