### ISSUE TITLE
Error after upgrade from PHP 5.3 to PHP 5.4

### ISSUE THREAD

**Issue by hydn79** [benjy/MegaMenu#4]
After upgrading to PHP 5.4 I get this error:
/home/xxxxxxx/public_html/app/code/local/DevBlog/MegaMenu/Block/ThreeColumns.php on line 101

line 101 is:
if($counter == self::$this->numBrands) {

Is there there an easy fix?

Thanks for your help.

**Comment by benjy** [comment]
self::$this-> is wrong. Change to $this->numBrands.

I should note, i'm no longer supporting this module.
